name: Upload Binaries

on:
  release:

jobs:
  upload-bins:
    # only upload binaries if the tag is a`tokio-console` release
    if: contains(github.ref, 'tokio-console')
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: tokio-console
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}